### ISSUE TITLE
WeMo SDK causes or app to crash

### ISSUE THREAD

**Issue by fabianbergmark** [BelkinWemo/Wemo-Discovery-SDK#8]
Since we included the WeMo SDK, we have received a lot of crash reports similar to:

{Cyber.SSDPNotifySocket/192.168.1.49:1900 -> 239.255.255.250:1900} {IllegalArgumentException} (@java.io.BufferedReader:<init>:109) java.lang.IllegalArgumentException: size <= 0 at java.io.BufferedReader.<init>(BufferedReader.java:109) at java.io.LineNumberReader.<init>(LineNumberReader.java:59) at org.cybergarage.http.HTTPHeader.getValue(SourceFile:120) at org.cybergarage.http.HTTPHeader.getValue(SourceFile:126) at org.cybergarage.upnp.ssdp.SSDPPacket.getHost(SourceFile:138) at org.cybergarage.upnp.ssdp.SSDPPacket.getHostInetAddress(SourceFile:193) at org.cybergarage.upnp.ssdp.SSDPNotifySocket.run(SourceFile:134) at java.lang.Thread.run(Thread.java:818)

After some investigation it turned out to be a .class file included in the WeMo SDK.

**Comment by iheart2code** [comment]
This SDK is a buggy mess and they have no intention of fixing it. Ditch the SDK, search around for python implementations of the WeMo SDK and try to reproduce the HTTP calls that are being made.

**Comment by fabianbergmark** [comment]
had to do the same for LIFX. Whats the problem with releasing working SDKs?
